ktor:
  development: true
  deployment:
    port: 8080
    host: "localhost"
  application:
    modules:
      - it.unicam.cs.pawm.ApplicationKt.module

jwt:
  privateKey: "$PRIVATE_KEY"
  issuer: "http://localhost:8080/"
  audience: ""