ktor:
  development: true
  deployment:
    port: 8080
    host: "localhost"
  application:
    modules:
      - it.unicam.cs.pawm.ApplicationKt.module

jwt:
  refSecret: "$REF_SECRET"
  accSecret: "$ACC_SECRET"
  issuer: "http://localhost:8080/"